-- Intentionally empty as a plain SQL statement. The one-time, idempotent
-- backfill of budget_item_category_links / savings_goal_category_links
-- from the old single-slot apiCategoryId columns (see 0035) needs real
-- per-row counting + structured logging so whoever runs this in prod knows
-- exactly how many links are guesses (see the advisor review referenced in
-- CHANGELOG.md [0.7.11]) — that needs application code, not raw SQL, so it
-- lives in db-migrate.ts's backfillCategoryLinks(), gated on this
-- migration's tag exactly like backfillHistoricalSalaries() is gated on
-- 0016_drop_salary_ledger_tables. This file still needs to exist (and be
-- non-empty, so drizzle-kit doesn't skip recording it) so the migration
-- journal has a real hash to track.
SELECT 1;
