#!/usr/bin/env bash
# One-command developer setup for ledgr (v0.5 expert-review M23).
#
# Brings a fresh clone from "git clone" to a running dev server in
# under 5 minutes by automating: dep install, env file creation,
# database initialization, and migration runs. Idempotent — safe to
# re-run on an existing checkout.
#
# Usage:
#   ./scripts/setup-dev.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

step() {
  echo -e "\n${BOLD}=> $*${NC}"
}

ok() {
  echo -e "${GREEN}✓ $*${NC}"
}

warn() {
  echo -e "${YELLOW}! $*${NC}"
}

err() {
  echo -e "${RED}✗ $*${NC}" >&2
}

# ── Pre-flight checks ────────────────────────────────────────────────

step "Checking prerequisites"

if ! command -v node >/dev/null 2>&1; then
  err "node not found. Install Node 22+ from https://nodejs.org/"
  exit 1
fi
NODE_MAJOR="$(node -e 'console.log(process.versions.node.split(".")[0])')"
if [[ "$NODE_MAJOR" -lt 22 ]]; then
  err "Node $NODE_MAJOR is too old. Need Node 22 or newer."
  exit 1
fi
ok "node $(node -v)"

if ! command -v pnpm >/dev/null 2>&1; then
  warn "pnpm not found — installing via corepack"
  corepack enable
  corepack prepare pnpm@latest --activate
fi
ok "pnpm $(pnpm -v)"

# ── Step 1: Install dependencies ──────────────────────────────────────

step "Installing dependencies (pnpm install)"
if [[ -d node_modules && -f node_modules/.modules.yaml ]]; then
  ok "node_modules already populated — running install to catch lockfile drift"
fi
pnpm install --frozen-lockfile
ok "Dependencies installed"

# ── Step 2: Environment file ──────────────────────────────────────────

step "Setting up .env"

if [[ ! -f .env ]]; then
  if [[ -f .env.example ]]; then
    cp .env.example .env
    ok "Created .env from .env.example"
  else
    cat > .env <<'EOF'
# Generated by scripts/setup-dev.sh
# Defaults are dev-mode safe — DO NOT use in production.

# SQLite (default) — for postgres, set DATABASE_URL=postgresql://...
# DATABASE_URL=postgresql://postgres:postgres@localhost:5432/ledgr

# Auth (dev-mode bypass)
NEXTAUTH_SECRET=dev-secret-do-not-use-in-production-32-chars-min
ALLOW_DEV_MODE=true

# At-rest encryption key for API connections (32 bytes base64).
# Generate a fresh one with:
#   node -e 'console.log(require("crypto").randomBytes(32).toString("base64"))'
ENCRYPTION_KEY=

# Optional: cron secret for /api/health/detailed (32+ chars)
# CRON_SECRET=
EOF
    ok "Created .env with dev defaults"
  fi

  # Generate ENCRYPTION_KEY if not set
  if grep -q '^ENCRYPTION_KEY=$' .env; then
    KEY="$(node -e 'console.log(require("crypto").randomBytes(32).toString("base64"))')"
    # Use a portable sed-in-place
    if [[ "$(uname -s)" == "Darwin" ]]; then
      sed -i '' "s|^ENCRYPTION_KEY=$|ENCRYPTION_KEY=$KEY|" .env
    else
      sed -i "s|^ENCRYPTION_KEY=$|ENCRYPTION_KEY=$KEY|" .env
    fi
    ok "Generated ENCRYPTION_KEY"
  fi
else
  ok ".env already exists — leaving it alone"
fi

# ── Step 3: Database migrations ───────────────────────────────────────

step "Running database migrations (db:migrate)"
mkdir -p data
if pnpm db:migrate; then
  ok "Migrations applied"
else
  err "Migrations failed. If this is a fresh checkout, check that"
  err "DATABASE_URL is set correctly in .env (or unset for SQLite)."
  exit 1
fi

# ── Step 4: Verify ────────────────────────────────────────────────────

step "Verifying setup"

if pnpm docs:verify >/dev/null 2>&1; then
  ok "docs:verify passes"
else
  warn "docs:verify reports drift — run 'pnpm docs:update' to refresh"
fi

# ── Done ──────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Setup complete!${NC} Next steps:"
echo "  pnpm dev               # Start the dev server on http://localhost:3000"
echo "  pnpm test              # Run the full test suite"
echo "  pnpm test --run <path> # Run a single test file"
echo ""
echo "See CONTRIBUTING.md for the full development workflow."
