import type { DemoProfile } from "../types";

export const debtPayoffProfile: DemoProfile = {
  slug: "debt-payoff",
  name: "Debt Payoff Journey",
  description:
    "Moderate income, significant debt, focused on building emergency fund and paying down loans.",
  keyStats: { income: "$62,000", portfolioSize: "$12,000", savingsRate: "8%" },

  people: [{ name: "Casey", dateOfBirth: "1993-02-20", isPrimaryUser: true }],

  jobs: [
    {
      personName: "Casey",
      employerName: "ConsultingFirm",
      title: "Project Coordinator",
      annualSalary: "62000",
      payPeriod: "biweekly",
      payWeek: "even",
      startDate: "2021-09-01",
      anchorPayDate: "2026-01-10",
      endDate: null,
      bonusPercent: "0",
      bonusMonth: null,
      w4FilingStatus: "Single",
    },
  ],

  budgetProfiles: [
    {
      name: "Debt Focus",
      isActive: true,
      columnLabels: ["Bare Minimum", "Normal", "After Payoff"],
      columnMonths: null,
    },
  ],

  budgetItems: [
    {
      profileName: "Debt Focus",
      category: "Housing",
      subcategory: "Rent",
      isEssential: true,
      amounts: [1100, 1100, 1100],
    },
    {
      profileName: "Debt Focus",
      category: "Housing",
      subcategory: "Utilities",
      isEssential: true,
      amounts: [100, 130, 150],
    },
    {
      profileName: "Debt Focus",
      category: "Housing",
      subcategory: "Insurance",
      isEssential: true,
      amounts: [25, 25, 25],
    },
    {
      profileName: "Debt Focus",
      category: "Food",
      subcategory: "Groceries",
      isEssential: true,
      amounts: [250, 350, 450],
    },
    {
      profileName: "Debt Focus",
      category: "Food",
      subcategory: "Dining Out",
      isEssential: false,
      amounts: [0, 50, 150],
    },
    {
      profileName: "Debt Focus",
      category: "Transportation",
      subcategory: "Car Payment",
      isEssential: true,
      amounts: [280, 280, 280],
    },
    {
      profileName: "Debt Focus",
      category: "Transportation",
      subcategory: "Gas & Insurance",
      isEssential: true,
      amounts: [130, 160, 180],
    },
    {
      profileName: "Debt Focus",
      category: "Debt",
      subcategory: "Student Loans",
      isEssential: true,
      amounts: [450, 450, 0],
    },
    {
      profileName: "Debt Focus",
      category: "Debt",
      subcategory: "Credit Card",
      isEssential: true,
      amounts: [200, 200, 0],
    },
    {
      profileName: "Debt Focus",
      category: "Health",
      subcategory: "Insurance Premium",
      isEssential: true,
      amounts: [80, 80, 80],
    },
    {
      profileName: "Debt Focus",
      category: "Personal",
      subcategory: "Subscriptions",
      isEssential: false,
      amounts: [15, 30, 50],
    },
    {
      profileName: "Debt Focus",
      category: "Personal",
      subcategory: "Entertainment",
      isEssential: false,
      amounts: [20, 60, 150],
    },
  ],

  savingsGoals: [
    {
      name: "Emergency Fund",
      targetAmount: null,
      targetMonths: 3,
      priority: 1,
      isEmergencyFund: true,
      monthlyContribution: "250",
      allocationPercent: null,
    },
    {
      name: "Car Repair Fund",
      targetAmount: "1500",
      targetMonths: null,
      priority: 2,
      isEmergencyFund: false,
      monthlyContribution: "100",
      allocationPercent: null,
    },
    {
      name: "Debt Snowball",
      targetAmount: "5000",
      targetMonths: null,
      priority: 3,
      isEmergencyFund: false,
      monthlyContribution: "150",
      allocationPercent: null,
    },
  ],

  savingsMonthly: [
    // Emergency Fund: grew from $3000 to $5000 over 12 months
    { goalName: "Emergency Fund", monthDate: "2025-04-01", balance: "3000" },
    { goalName: "Emergency Fund", monthDate: "2025-05-01", balance: "3150" },
    { goalName: "Emergency Fund", monthDate: "2025-06-01", balance: "3300" },
    { goalName: "Emergency Fund", monthDate: "2025-07-01", balance: "3450" },
    { goalName: "Emergency Fund", monthDate: "2025-08-01", balance: "3600" },
    { goalName: "Emergency Fund", monthDate: "2025-09-01", balance: "3800" },
    { goalName: "Emergency Fund", monthDate: "2025-10-01", balance: "3950" },
    { goalName: "Emergency Fund", monthDate: "2025-11-01", balance: "4100" },
    { goalName: "Emergency Fund", monthDate: "2025-12-01", balance: "4300" },
    { goalName: "Emergency Fund", monthDate: "2026-01-01", balance: "4550" },
    { goalName: "Emergency Fund", monthDate: "2026-02-01", balance: "4750" },
    { goalName: "Emergency Fund", monthDate: "2026-03-01", balance: "5000" },
    // Car Repair Fund: grew from $200 to $1000 over 12 months
    { goalName: "Car Repair Fund", monthDate: "2025-04-01", balance: "200" },
    { goalName: "Car Repair Fund", monthDate: "2025-05-01", balance: "275" },
    { goalName: "Car Repair Fund", monthDate: "2025-06-01", balance: "345" },
    { goalName: "Car Repair Fund", monthDate: "2025-07-01", balance: "420" },
    { goalName: "Car Repair Fund", monthDate: "2025-08-01", balance: "490" },
    { goalName: "Car Repair Fund", monthDate: "2025-09-01", balance: "560" },
    { goalName: "Car Repair Fund", monthDate: "2025-10-01", balance: "640" },
    { goalName: "Car Repair Fund", monthDate: "2025-11-01", balance: "715" },
    { goalName: "Car Repair Fund", monthDate: "2025-12-01", balance: "790" },
    { goalName: "Car Repair Fund", monthDate: "2026-01-01", balance: "865" },
    { goalName: "Car Repair Fund", monthDate: "2026-02-01", balance: "935" },
    { goalName: "Car Repair Fund", monthDate: "2026-03-01", balance: "1000" },
    { goalName: "Debt Snowball", monthDate: "2026-03-01", balance: "900" },
  ],

  contributionAccounts: [
    {
      personName: "Casey",
      accountType: "401k",
      taxTreatment: "pre_tax",
      contributionMethod: "percent_of_salary",
      contributionValue: "6",
      employerMatchType: "percent_of_contribution",
      employerMatchValue: "50",
      employerMaxMatchPct: "6",
      perfAccountLabel: "401(k) - ConsultingFirm",
    },
  ],

  portfolioSnapshots: [{ snapshotDate: "2026-03-01" }],

  portfolioAccounts: [
    {
      institution: "ConsultingFirm",
      accountType: "401k",
      taxType: "preTax",
      amount: "14000",
      label: null,
      ownerPersonName: "Casey",
      perfAccountLabel: "401(k) - ConsultingFirm",
    },
  ],

  performanceAccounts: [
    {
      institution: "ConsultingFirm",
      accountType: "401k",
      accountLabel: "401(k) - ConsultingFirm",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
  ],

  annualPerformance: [
    {
      category: "Retirement",
      year: 2023,
      beginningBalance: "0",
      totalContributions: "3720",
      yearlyGainLoss: "280",
      endingBalance: "4000",
      annualReturnPct: "0.075",
      employerContributions: "1240",
      fees: "20",
      lifetimeGains: "280",
      lifetimeContributions: "3720",
      lifetimeMatch: "1240",
    },
    {
      category: "Retirement",
      year: 2024,
      beginningBalance: "4000",
      totalContributions: "5580",
      yearlyGainLoss: "-1050",
      endingBalance: "8500",
      annualReturnPct: "0.032",
      employerContributions: "1860",
      fees: "30",
      lifetimeGains: "500",
      lifetimeContributions: "9000",
      lifetimeMatch: "3000",
    },
    {
      category: "Retirement",
      year: 2025,
      beginningBalance: "8500",
      totalContributions: "5580",
      yearlyGainLoss: "-2045",
      endingBalance: "12000",
      annualReturnPct: "0.035",
      employerContributions: "1860",
      fees: "35",
      lifetimeGains: "1455",
      lifetimeContributions: "14580",
      lifetimeMatch: "4860",
    },
  ],

  retirementSettings: {
    personName: "Casey",
    retirementAge: 65,
    endAge: 90,
    returnAfterRetirement: "0.05",
    annualInflation: "0.03",
    salaryAnnualIncrease: "0.025",
    withdrawalRate: "0.04",
    withdrawalStrategy: "fixed",
    socialSecurityMonthly: "1800",
    ssStartAge: 67,
  },

  returnRates: [
    { age: 25, rateOfReturn: "0.08" },
    { age: 50, rateOfReturn: "0.07" },
    { age: 65, rateOfReturn: "0.06" },
    { age: 80, rateOfReturn: "0.05" },
  ],

  mortgageLoans: [
    {
      name: "Primary Residence",
      isActive: true,
      principalAndInterest: "1350",
      interestRate: "0.0699",
      termYears: 30,
      originalLoanAmount: "220000",
      firstPaymentDate: "2022-01-01",
      propertyValuePurchase: "250000",
      propertyValueEstimated: "260000",
    },
  ],

  accountPerformance: [
    {
      year: 2024,
      institution: "ConsultingFirm",
      accountLabel: "401(k) - ConsultingFirm",
      ownerPersonName: "Casey",
      beginningBalance: "4000",
      totalContributions: "5580",
      yearlyGainLoss: "-1050",
      endingBalance: "8500",
      annualReturnPct: "0.032",
      employerContributions: "1860",
      fees: "30",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - ConsultingFirm",
    },
    {
      year: 2025,
      institution: "ConsultingFirm",
      accountLabel: "401(k) - ConsultingFirm",
      ownerPersonName: "Casey",
      beginningBalance: "8500",
      totalContributions: "5580",
      yearlyGainLoss: "-2045",
      endingBalance: "12000",
      annualReturnPct: "0.035",
      employerContributions: "1860",
      fees: "35",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - ConsultingFirm",
    },
    // 2026 YTD (Q1)
    {
      year: 2026,
      institution: "ConsultingFirm",
      accountLabel: "401(k) - ConsultingFirm",
      ownerPersonName: "Casey",
      beginningBalance: "12000",
      totalContributions: "1395",
      yearlyGainLoss: "140",
      endingBalance: "14000",
      annualReturnPct: "1.1",
      employerContributions: "465",
      fees: "8",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - ConsultingFirm",
    },
  ],

  otherAssetItems: [
    { name: "Ford F-150", year: 2024, value: "25000", note: "Work truck" },
    { name: "Ford F-150", year: 2025, value: "22000", note: "Depreciation" },
  ],

  propertyTaxes: [
    {
      loanName: "Primary Residence",
      year: 2024,
      assessedValue: "245000",
      taxAmount: "3200",
      note: null,
    },
    {
      loanName: "Primary Residence",
      year: 2025,
      assessedValue: "255000",
      taxAmount: "3350",
      note: null,
    },
  ],

  homeImprovements: [{ year: 2024, description: "Roof repair", cost: "4500" }],

  netWorthAnnual: [
    {
      yearEndDate: "2023-12-31",
      grossIncome: "60000",
      combinedAgi: "56400",
      cash: "1500",
      houseValue: "0",
      retirementTotal: "2000",
      portfolioTotal: "2000",
      mortgageBalance: "0",
    },
    {
      yearEndDate: "2024-12-31",
      grossIncome: "62000",
      combinedAgi: "58280",
      cash: "3000",
      houseValue: "0",
      retirementTotal: "8500",
      portfolioTotal: "8500",
      mortgageBalance: "0",
    },
    {
      yearEndDate: "2025-12-31",
      grossIncome: "62000",
      combinedAgi: "58280",
      cash: "3700",
      houseValue: "0",
      retirementTotal: "12000",
      portfolioTotal: "12000",
      mortgageBalance: "0",
    },
  ],

  appSettings: [
    { key: "budget_active_column", value: 0 },
    { key: "efund_budget_column", value: 0 },
  ],
};
