import type { DemoProfile } from "../types";

export const dualIncomeFamilyProfile: DemoProfile = {
  slug: "dual-income-family",
  name: "Dual Income Family",
  description:
    "Two incomes, mortgage, kids, moderate portfolio — mid-career financial planning.",
  keyStats: {
    income: "$195,000",
    portfolioSize: "$420,000",
    savingsRate: "22%",
  },

  people: [
    { name: "Jordan", dateOfBirth: "1988-04-12", isPrimaryUser: true },
    { name: "Taylor", dateOfBirth: "1990-09-25", isPrimaryUser: false },
  ],

  jobs: [
    {
      personName: "Jordan",
      employerName: "BigCo",
      title: "Engineering Manager",
      annualSalary: "125000",
      payPeriod: "biweekly",
      payWeek: "even",
      startDate: "2016-03-01",
      anchorPayDate: "2026-01-10",
      endDate: null,
      bonusPercent: "0.10",
      bonusMonth: 3,
      w4FilingStatus: "MFJ",
    },
    {
      personName: "Taylor",
      employerName: "AdAgency",
      title: "Marketing Director",
      annualSalary: "70000",
      payPeriod: "semimonthly",
      payWeek: "na",
      startDate: "2018-01-15",
      anchorPayDate: null,
      endDate: null,
      bonusPercent: "0",
      bonusMonth: null,
      w4FilingStatus: "MFJ",
    },
  ],

  budgetProfiles: [
    {
      name: "Family Budget",
      isActive: true,
      columnLabels: ["Lean", "Normal", "Comfortable"],
      columnMonths: null,
    },
  ],

  budgetItems: [
    {
      profileName: "Family Budget",
      category: "Housing",
      subcategory: "Mortgage",
      isEssential: true,
      amounts: [2100, 2100, 2100],
    },
    {
      profileName: "Family Budget",
      category: "Housing",
      subcategory: "Property Tax",
      isEssential: true,
      amounts: [450, 450, 450],
    },
    {
      profileName: "Family Budget",
      category: "Housing",
      subcategory: "Utilities",
      isEssential: true,
      amounts: [250, 300, 350],
    },
    {
      profileName: "Family Budget",
      category: "Housing",
      subcategory: "Home Insurance",
      isEssential: true,
      amounts: [150, 150, 150],
    },
    {
      profileName: "Family Budget",
      category: "Housing",
      subcategory: "Maintenance",
      isEssential: false,
      amounts: [100, 200, 350],
    },
    {
      profileName: "Family Budget",
      category: "Food",
      subcategory: "Groceries",
      isEssential: true,
      amounts: [600, 800, 1000],
    },
    {
      profileName: "Family Budget",
      category: "Food",
      subcategory: "Dining Out",
      isEssential: false,
      amounts: [100, 250, 400],
    },
    {
      profileName: "Family Budget",
      category: "Transportation",
      subcategory: "Car Payments",
      isEssential: true,
      amounts: [550, 550, 550],
    },
    {
      profileName: "Family Budget",
      category: "Transportation",
      subcategory: "Gas & Insurance",
      isEssential: true,
      amounts: [300, 350, 400],
    },
    {
      profileName: "Family Budget",
      category: "Children",
      subcategory: "Childcare",
      isEssential: true,
      amounts: [1200, 1200, 1200],
    },
    {
      profileName: "Family Budget",
      category: "Children",
      subcategory: "Activities",
      isEssential: false,
      amounts: [100, 200, 350],
    },
    {
      profileName: "Family Budget",
      category: "Health",
      subcategory: "Insurance Premium",
      isEssential: true,
      amounts: [400, 400, 400],
    },
    {
      profileName: "Family Budget",
      category: "Health",
      subcategory: "Medical OOP",
      isEssential: false,
      amounts: [50, 100, 200],
    },
    {
      profileName: "Family Budget",
      category: "Personal",
      subcategory: "Subscriptions",
      isEssential: false,
      amounts: [50, 80, 120],
    },
    {
      profileName: "Family Budget",
      category: "Personal",
      subcategory: "Entertainment",
      isEssential: false,
      amounts: [100, 200, 350],
    },
    {
      profileName: "Family Budget",
      category: "Giving",
      subcategory: "Charitable",
      isEssential: false,
      amounts: [200, 400, 600],
    },
  ],

  savingsGoals: [
    {
      name: "Emergency Fund",
      targetAmount: null,
      targetMonths: 6,
      priority: 1,
      isEmergencyFund: true,
      monthlyContribution: "800",
      allocationPercent: null,
    },
    {
      name: "Family Vacation",
      targetAmount: "8000",
      targetMonths: null,
      priority: 2,
      isEmergencyFund: false,
      monthlyContribution: "400",
      allocationPercent: null,
    },
    {
      name: "Home Repairs",
      targetAmount: "15000",
      targetMonths: null,
      priority: 3,
      isEmergencyFund: false,
      monthlyContribution: "300",
      allocationPercent: null,
    },
    {
      name: "Kids College",
      targetAmount: "50000",
      targetMonths: null,
      priority: 4,
      isEmergencyFund: false,
      monthlyContribution: "500",
      allocationPercent: null,
    },
  ],

  savingsMonthly: [
    // Emergency Fund: grew from $15,000 to $20,000 over 12 months
    { goalName: "Emergency Fund", monthDate: "2025-04-01", balance: "15000" },
    { goalName: "Emergency Fund", monthDate: "2025-05-01", balance: "15450" },
    { goalName: "Emergency Fund", monthDate: "2025-06-01", balance: "15900" },
    { goalName: "Emergency Fund", monthDate: "2025-07-01", balance: "16350" },
    { goalName: "Emergency Fund", monthDate: "2025-08-01", balance: "16800" },
    { goalName: "Emergency Fund", monthDate: "2025-09-01", balance: "17250" },
    { goalName: "Emergency Fund", monthDate: "2025-10-01", balance: "17700" },
    { goalName: "Emergency Fund", monthDate: "2025-11-01", balance: "18100" },
    { goalName: "Emergency Fund", monthDate: "2025-12-01", balance: "18600" },
    { goalName: "Emergency Fund", monthDate: "2026-01-01", balance: "19100" },
    { goalName: "Emergency Fund", monthDate: "2026-02-01", balance: "19550" },
    { goalName: "Emergency Fund", monthDate: "2026-03-01", balance: "20000" },
    // Kids College: grew from $5,000 to $8,000 over 12 months
    { goalName: "Kids College", monthDate: "2025-04-01", balance: "5000" },
    { goalName: "Kids College", monthDate: "2025-05-01", balance: "5270" },
    { goalName: "Kids College", monthDate: "2025-06-01", balance: "5550" },
    { goalName: "Kids College", monthDate: "2025-07-01", balance: "5820" },
    { goalName: "Kids College", monthDate: "2025-08-01", balance: "6090" },
    { goalName: "Kids College", monthDate: "2025-09-01", balance: "6360" },
    { goalName: "Kids College", monthDate: "2025-10-01", balance: "6640" },
    { goalName: "Kids College", monthDate: "2025-11-01", balance: "6910" },
    { goalName: "Kids College", monthDate: "2025-12-01", balance: "7180" },
    { goalName: "Kids College", monthDate: "2026-01-01", balance: "7450" },
    { goalName: "Kids College", monthDate: "2026-02-01", balance: "7730" },
    { goalName: "Kids College", monthDate: "2026-03-01", balance: "8000" },
    // Family Vacation: grew from $1,000 to $3,000 over 12 months
    { goalName: "Family Vacation", monthDate: "2025-04-01", balance: "1000" },
    { goalName: "Family Vacation", monthDate: "2025-05-01", balance: "1180" },
    { goalName: "Family Vacation", monthDate: "2025-06-01", balance: "1360" },
    { goalName: "Family Vacation", monthDate: "2025-07-01", balance: "1550" },
    { goalName: "Family Vacation", monthDate: "2025-08-01", balance: "1730" },
    { goalName: "Family Vacation", monthDate: "2025-09-01", balance: "1910" },
    { goalName: "Family Vacation", monthDate: "2025-10-01", balance: "2090" },
    { goalName: "Family Vacation", monthDate: "2025-11-01", balance: "2270" },
    { goalName: "Family Vacation", monthDate: "2025-12-01", balance: "2460" },
    { goalName: "Family Vacation", monthDate: "2026-01-01", balance: "2640" },
    { goalName: "Family Vacation", monthDate: "2026-02-01", balance: "2820" },
    { goalName: "Family Vacation", monthDate: "2026-03-01", balance: "3000" },
    // Home Repairs (existing single snapshot)
    { goalName: "Home Repairs", monthDate: "2026-03-01", balance: "8500" },
  ],

  contributionAccounts: [
    {
      personName: "Jordan",
      accountType: "401k",
      taxTreatment: "pre_tax",
      contributionMethod: "percent_of_salary",
      contributionValue: "15",
      employerMatchType: "percent_of_contribution",
      employerMatchValue: "100",
      employerMaxMatchPct: "4",
      perfAccountLabel: "401(k) - BigCo",
    },
    {
      personName: "Jordan",
      accountType: "ira",
      taxTreatment: "tax_free",
      contributionMethod: "fixed_annual",
      contributionValue: "7000",
      employerMatchType: "none",
      employerMatchValue: null,
      employerMaxMatchPct: null,
      perfAccountLabel: "Roth IRA - Jordan",
    },
    {
      personName: "Taylor",
      accountType: "401k",
      taxTreatment: "pre_tax",
      contributionMethod: "percent_of_salary",
      contributionValue: "10",
      employerMatchType: "percent_of_contribution",
      employerMatchValue: "50",
      employerMaxMatchPct: "6",
      perfAccountLabel: "401(k) - AdAgency",
    },
    {
      personName: "Jordan",
      accountType: "hsa",
      taxTreatment: "hsa",
      contributionMethod: "fixed_annual",
      contributionValue: "8300",
      employerMatchType: "none",
      employerMatchValue: null,
      employerMaxMatchPct: null,
      perfAccountLabel: "HSA",
    },
  ],

  portfolioSnapshots: [{ snapshotDate: "2026-03-01" }],

  portfolioAccounts: [
    {
      institution: "BigCo",
      accountType: "401k",
      taxType: "preTax",
      amount: "222000",
      label: null,
      ownerPersonName: "Jordan",
      perfAccountLabel: "401(k) - BigCo",
    },
    {
      institution: "AdAgency",
      accountType: "401k",
      taxType: "preTax",
      amount: "51500",
      label: null,
      ownerPersonName: "Taylor",
      perfAccountLabel: "401(k) - AdAgency",
    },
    {
      institution: "Vanguard",
      accountType: "ira",
      taxType: "taxFree",
      amount: "64500",
      label: "Jordan",
      ownerPersonName: "Jordan",
      perfAccountLabel: "Roth IRA - Jordan",
    },
    {
      institution: "Fidelity",
      accountType: "hsa",
      taxType: "hsa",
      amount: "39000",
      label: null,
      ownerPersonName: "Jordan",
      perfAccountLabel: "HSA",
    },
    {
      institution: "Schwab",
      accountType: "brokerage",
      taxType: "afterTax",
      amount: "137000",
      label: null,
      ownerPersonName: "Jordan",
      perfAccountLabel: "Brokerage",
    },
  ],

  performanceAccounts: [
    {
      institution: "BigCo",
      accountType: "401k",
      accountLabel: "401(k) - BigCo",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "AdAgency",
      accountType: "401k",
      accountLabel: "401(k) - AdAgency",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "Vanguard",
      accountType: "ira",
      accountLabel: "Roth IRA - Jordan",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "Fidelity",
      accountType: "hsa",
      accountLabel: "HSA",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "Schwab",
      accountType: "brokerage",
      accountLabel: "Brokerage",
      ownershipType: "individual",
      parentCategory: "Portfolio",
      label: null,
      isActive: true,
    },
  ],

  annualPerformance: [
    {
      category: "Retirement",
      year: 2023,
      beginningBalance: "240000",
      totalContributions: "42000",
      yearlyGainLoss: "38000",
      endingBalance: "320000",
      annualReturnPct: "0.134",
      employerContributions: "7800",
      fees: "180",
      lifetimeGains: "49750",
      lifetimeContributions: "152250",
      lifetimeMatch: "26500",
    },
    {
      category: "Portfolio",
      year: 2023,
      beginningBalance: "75000",
      totalContributions: "18000",
      yearlyGainLoss: "12000",
      endingBalance: "105000",
      annualReturnPct: "0.129",
      employerContributions: "0",
      fees: "50",
      lifetimeGains: "20000",
      lifetimeContributions: "85000",
      lifetimeMatch: "0",
    },
    {
      category: "Retirement",
      year: 2024,
      beginningBalance: "320000",
      totalContributions: "47750",
      yearlyGainLoss: "22250",
      endingBalance: "380000",
      annualReturnPct: "0.057",
      employerContributions: "8500",
      fees: "200",
      lifetimeGains: "72000",
      lifetimeContributions: "200000",
      lifetimeMatch: "35000",
    },
    {
      category: "Retirement",
      year: 2025,
      beginningBalance: "380000",
      totalContributions: "49000",
      yearlyGainLoss: "19210",
      endingBalance: "420000",
      annualReturnPct: "0.042",
      employerContributions: "8700",
      fees: "210",
      lifetimeGains: "91210",
      lifetimeContributions: "249000",
      lifetimeMatch: "43700",
    },
    {
      category: "Portfolio",
      year: 2024,
      beginningBalance: "105000",
      totalContributions: "20000",
      yearlyGainLoss: "8500",
      endingBalance: "133500",
      annualReturnPct: "0.068",
      employerContributions: "0",
      fees: "60",
      lifetimeGains: "28500",
      lifetimeContributions: "105000",
      lifetimeMatch: "0",
    },
    {
      category: "Portfolio",
      year: 2025,
      beginningBalance: "133500",
      totalContributions: "22000",
      yearlyGainLoss: "6500",
      endingBalance: "162000",
      annualReturnPct: "0.042",
      employerContributions: "0",
      fees: "65",
      lifetimeGains: "35000",
      lifetimeContributions: "127000",
      lifetimeMatch: "0",
    },
  ],

  retirementSettings: {
    personName: "Jordan",
    retirementAge: 58,
    endAge: 92,
    returnAfterRetirement: "0.05",
    annualInflation: "0.03",
    salaryAnnualIncrease: "0.03",
    withdrawalRate: "0.038",
    withdrawalStrategy: "guyton_klinger",
    socialSecurityMonthly: "3200",
    ssStartAge: 67,
  },

  returnRates: [
    { age: 25, rateOfReturn: "0.08" },
    { age: 50, rateOfReturn: "0.07" },
    { age: 58, rateOfReturn: "0.065" },
    { age: 70, rateOfReturn: "0.055" },
    { age: 85, rateOfReturn: "0.045" },
  ],

  mortgageLoans: [
    {
      name: "Primary Residence",
      isActive: true,
      principalAndInterest: "2100",
      interestRate: "0.0625",
      termYears: 30,
      originalLoanAmount: "380000",
      firstPaymentDate: "2021-06-01",
      propertyValuePurchase: "485000",
      propertyValueEstimated: null,
    },
  ],

  accountPerformance: [
    // 2024
    {
      year: 2024,
      institution: "BigCo",
      accountLabel: "401(k) - BigCo",
      ownerPersonName: "Jordan",
      beginningBalance: "155000",
      totalContributions: "18750",
      yearlyGainLoss: "11250",
      endingBalance: "185000",
      annualReturnPct: "0.065",
      employerContributions: "5000",
      fees: "90",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - BigCo",
    },
    {
      year: 2024,
      institution: "Vanguard",
      accountLabel: "Roth IRA - Jordan",
      ownerPersonName: "Jordan",
      beginningBalance: "42000",
      totalContributions: "7000",
      yearlyGainLoss: "3500",
      endingBalance: "52500",
      annualReturnPct: "0.072",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA - Jordan",
    },
    {
      year: 2024,
      institution: "AdAgency",
      accountLabel: "401(k) - AdAgency",
      ownerPersonName: "Taylor",
      beginningBalance: "30000",
      totalContributions: "7000",
      yearlyGainLoss: "2500",
      endingBalance: "39500",
      annualReturnPct: "0.068",
      employerContributions: "2100",
      fees: "60",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - AdAgency",
    },
    {
      year: 2024,
      institution: "Fidelity",
      accountLabel: "HSA",
      ownerPersonName: "Jordan",
      beginningBalance: "18000",
      totalContributions: "8300",
      yearlyGainLoss: "1200",
      endingBalance: "27500",
      annualReturnPct: "0.044",
      employerContributions: "0",
      fees: "25",
      parentCategory: "Retirement",
      perfAccountLabel: "HSA",
    },
    {
      year: 2024,
      institution: "Schwab",
      accountLabel: "Brokerage",
      ownerPersonName: "Jordan",
      beginningBalance: "95000",
      totalContributions: "12000",
      yearlyGainLoss: "6500",
      endingBalance: "113500",
      annualReturnPct: "0.061",
      employerContributions: "0",
      fees: "35",
      parentCategory: "Portfolio",
      perfAccountLabel: "Brokerage",
    },
    // 2025
    {
      year: 2025,
      institution: "BigCo",
      accountLabel: "401(k) - BigCo",
      ownerPersonName: "Jordan",
      beginningBalance: "185000",
      totalContributions: "19500",
      yearlyGainLoss: "8500",
      endingBalance: "213000",
      annualReturnPct: "0.042",
      employerContributions: "5200",
      fees: "95",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - BigCo",
    },
    {
      year: 2025,
      institution: "Vanguard",
      accountLabel: "Roth IRA - Jordan",
      ownerPersonName: "Jordan",
      beginningBalance: "52500",
      totalContributions: "7000",
      yearlyGainLoss: "2500",
      endingBalance: "62000",
      annualReturnPct: "0.042",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA - Jordan",
    },
    {
      year: 2025,
      institution: "AdAgency",
      accountLabel: "401(k) - AdAgency",
      ownerPersonName: "Taylor",
      beginningBalance: "39500",
      totalContributions: "7200",
      yearlyGainLoss: "1800",
      endingBalance: "48500",
      annualReturnPct: "0.039",
      employerContributions: "2160",
      fees: "65",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - AdAgency",
    },
    {
      year: 2025,
      institution: "Fidelity",
      accountLabel: "HSA",
      ownerPersonName: "Jordan",
      beginningBalance: "27500",
      totalContributions: "8300",
      yearlyGainLoss: "700",
      endingBalance: "36500",
      annualReturnPct: "0.020",
      employerContributions: "0",
      fees: "25",
      parentCategory: "Retirement",
      perfAccountLabel: "HSA",
    },
    {
      year: 2025,
      institution: "Schwab",
      accountLabel: "Brokerage",
      ownerPersonName: "Jordan",
      beginningBalance: "113500",
      totalContributions: "14000",
      yearlyGainLoss: "4500",
      endingBalance: "132000",
      annualReturnPct: "0.035",
      employerContributions: "0",
      fees: "40",
      parentCategory: "Portfolio",
      perfAccountLabel: "Brokerage",
    },
    // 2026 YTD (Q1)
    {
      year: 2026,
      institution: "BigCo",
      accountLabel: "401(k) - BigCo",
      ownerPersonName: "Jordan",
      beginningBalance: "213000",
      totalContributions: "4875",
      yearlyGainLoss: "2825",
      endingBalance: "222000",
      annualReturnPct: "0.013",
      employerContributions: "1300",
      fees: "24",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - BigCo",
    },
    {
      year: 2026,
      institution: "Vanguard",
      accountLabel: "Roth IRA - Jordan",
      ownerPersonName: "Jordan",
      beginningBalance: "62000",
      totalContributions: "1750",
      yearlyGainLoss: "750",
      endingBalance: "64500",
      annualReturnPct: "0.012",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA - Jordan",
    },
    {
      year: 2026,
      institution: "AdAgency",
      accountLabel: "401(k) - AdAgency",
      ownerPersonName: "Taylor",
      beginningBalance: "48500",
      totalContributions: "1800",
      yearlyGainLoss: "660",
      endingBalance: "51500",
      annualReturnPct: "0.013",
      employerContributions: "540",
      fees: "16",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) - AdAgency",
    },
    {
      year: 2026,
      institution: "Fidelity",
      accountLabel: "HSA",
      ownerPersonName: "Jordan",
      beginningBalance: "36500",
      totalContributions: "2075",
      yearlyGainLoss: "425",
      endingBalance: "39000",
      annualReturnPct: "0.011",
      employerContributions: "0",
      fees: "6",
      parentCategory: "Retirement",
      perfAccountLabel: "HSA",
    },
    {
      year: 2026,
      institution: "Schwab",
      accountLabel: "Brokerage",
      ownerPersonName: "Jordan",
      beginningBalance: "132000",
      totalContributions: "3500",
      yearlyGainLoss: "1500",
      endingBalance: "137000",
      annualReturnPct: "0.011",
      employerContributions: "0",
      fees: "10",
      parentCategory: "Portfolio",
      perfAccountLabel: "Brokerage",
    },
  ],

  otherAssetItems: [
    { name: "Toyota RAV4", year: 2024, value: "32000", note: "Purchased 2023" },
    { name: "Toyota RAV4", year: 2025, value: "28000", note: "Depreciation" },
    { name: "Honda Accord", year: 2024, value: "22000", note: "Taylor's car" },
    { name: "Honda Accord", year: 2025, value: "19000", note: "Depreciation" },
  ],

  propertyTaxes: [
    {
      loanName: "Primary Residence",
      year: 2023,
      assessedValue: "380000",
      taxAmount: "4560",
      note: null,
    },
    {
      loanName: "Primary Residence",
      year: 2024,
      assessedValue: "395000",
      taxAmount: "4740",
      note: null,
    },
    {
      loanName: "Primary Residence",
      year: 2025,
      assessedValue: "410000",
      taxAmount: "4920",
      note: null,
    },
  ],

  homeImprovements: [
    { year: 2023, description: "Fence installation", cost: "5500" },
    { year: 2024, description: "Bathroom remodel", cost: "12000" },
  ],

  netWorthAnnual: [
    {
      yearEndDate: "2022-12-31",
      grossIncome: "180000",
      combinedAgi: "155000",
      cash: "18000",
      houseValue: "420000",
      retirementTotal: "240000",
      portfolioTotal: "240000",
      mortgageBalance: "360000",
    },
    {
      yearEndDate: "2023-12-31",
      grossIncome: "185000",
      combinedAgi: "160000",
      cash: "22000",
      houseValue: "450000",
      retirementTotal: "310000",
      portfolioTotal: "310000",
      mortgageBalance: "345000",
    },
    {
      yearEndDate: "2024-12-31",
      grossIncome: "190000",
      combinedAgi: "163000",
      cash: "35000",
      houseValue: "470000",
      retirementTotal: "418000",
      portfolioTotal: "418000",
      mortgageBalance: "325000",
    },
    {
      yearEndDate: "2025-12-31",
      grossIncome: "195000",
      combinedAgi: "168000",
      cash: "47700",
      houseValue: "485000",
      retirementTotal: "492000",
      portfolioTotal: "492000",
      mortgageBalance: "310000",
    },
  ],

  appSettings: [
    { key: "budget_active_column", value: 1 },
    { key: "efund_budget_column", value: 0 },
  ],
};
