import type { DemoProfile } from "../types";

export const earlyRetirementProfile: DemoProfile = {
  slug: "early-retirement",
  name: "FIRE Pursuer",
  description:
    "High income, aggressive savings rate, targeting early retirement at 45.",
  keyStats: {
    income: "$240,000",
    portfolioSize: "$850,000",
    savingsRate: "45%",
  },

  people: [{ name: "Morgan", dateOfBirth: "1991-11-03", isPrimaryUser: true }],

  jobs: [
    {
      personName: "Morgan",
      employerName: "FAANG",
      title: "Staff Engineer",
      annualSalary: "240000",
      payPeriod: "biweekly",
      payWeek: "odd",
      startDate: "2015-08-01",
      anchorPayDate: "2026-01-03",
      endDate: null,
      bonusPercent: "0.15",
      bonusMonth: 2,
      w4FilingStatus: "Single",
    },
  ],

  budgetProfiles: [
    {
      name: "FIRE Budget",
      isActive: true,
      columnLabels: ["Coast", "Normal", "Fat FIRE"],
      columnMonths: null,
    },
  ],

  budgetItems: [
    {
      profileName: "FIRE Budget",
      category: "Housing",
      subcategory: "Mortgage",
      isEssential: true,
      amounts: [1800, 1800, 1800],
    },
    {
      profileName: "FIRE Budget",
      category: "Housing",
      subcategory: "Property Tax",
      isEssential: true,
      amounts: [350, 350, 350],
    },
    {
      profileName: "FIRE Budget",
      category: "Housing",
      subcategory: "Utilities",
      isEssential: true,
      amounts: [150, 200, 250],
    },
    {
      profileName: "FIRE Budget",
      category: "Housing",
      subcategory: "Insurance",
      isEssential: true,
      amounts: [120, 120, 120],
    },
    {
      profileName: "FIRE Budget",
      category: "Food",
      subcategory: "Groceries",
      isEssential: true,
      amounts: [300, 400, 600],
    },
    {
      profileName: "FIRE Budget",
      category: "Food",
      subcategory: "Dining Out",
      isEssential: false,
      amounts: [50, 150, 350],
    },
    {
      profileName: "FIRE Budget",
      category: "Transportation",
      subcategory: "Car",
      isEssential: true,
      amounts: [200, 250, 350],
    },
    {
      profileName: "FIRE Budget",
      category: "Health",
      subcategory: "Insurance & ACA",
      isEssential: true,
      amounts: [200, 350, 500],
    },
    {
      profileName: "FIRE Budget",
      category: "Personal",
      subcategory: "Travel",
      isEssential: false,
      amounts: [200, 500, 1200],
    },
    {
      profileName: "FIRE Budget",
      category: "Personal",
      subcategory: "Hobbies",
      isEssential: false,
      amounts: [50, 150, 300],
    },
    {
      profileName: "FIRE Budget",
      category: "Giving",
      subcategory: "Charitable",
      isEssential: false,
      amounts: [100, 300, 600],
    },
  ],

  savingsGoals: [
    {
      name: "Emergency Fund",
      targetAmount: null,
      targetMonths: 6,
      priority: 1,
      isEmergencyFund: true,
      monthlyContribution: "0",
      allocationPercent: null,
    },
    {
      name: "Sabbatical Fund",
      targetAmount: "20000",
      targetMonths: null,
      priority: 2,
      isEmergencyFund: false,
      monthlyContribution: "500",
      allocationPercent: null,
    },
  ],

  savingsMonthly: [
    { goalName: "Emergency Fund", monthDate: "2025-04-01", balance: "25000" },
    { goalName: "Emergency Fund", monthDate: "2025-05-01", balance: "25400" },
    { goalName: "Emergency Fund", monthDate: "2025-06-01", balance: "25850" },
    { goalName: "Emergency Fund", monthDate: "2025-07-01", balance: "26300" },
    { goalName: "Emergency Fund", monthDate: "2025-08-01", balance: "26700" },
    { goalName: "Emergency Fund", monthDate: "2025-09-01", balance: "27100" },
    { goalName: "Emergency Fund", monthDate: "2025-10-01", balance: "27500" },
    { goalName: "Emergency Fund", monthDate: "2025-11-01", balance: "28000" },
    { goalName: "Emergency Fund", monthDate: "2025-12-01", balance: "28500" },
    { goalName: "Emergency Fund", monthDate: "2026-01-01", balance: "29000" },
    { goalName: "Emergency Fund", monthDate: "2026-02-01", balance: "29500" },
    { goalName: "Emergency Fund", monthDate: "2026-03-01", balance: "30000" },
    { goalName: "Sabbatical Fund", monthDate: "2025-04-01", balance: "8000" },
    { goalName: "Sabbatical Fund", monthDate: "2025-05-01", balance: "8500" },
    { goalName: "Sabbatical Fund", monthDate: "2025-06-01", balance: "9050" },
    { goalName: "Sabbatical Fund", monthDate: "2025-07-01", balance: "9600" },
    { goalName: "Sabbatical Fund", monthDate: "2025-08-01", balance: "10100" },
    { goalName: "Sabbatical Fund", monthDate: "2025-09-01", balance: "10600" },
    { goalName: "Sabbatical Fund", monthDate: "2025-10-01", balance: "11100" },
    { goalName: "Sabbatical Fund", monthDate: "2025-11-01", balance: "11650" },
    { goalName: "Sabbatical Fund", monthDate: "2025-12-01", balance: "12200" },
    { goalName: "Sabbatical Fund", monthDate: "2026-01-01", balance: "12800" },
    { goalName: "Sabbatical Fund", monthDate: "2026-02-01", balance: "13400" },
    { goalName: "Sabbatical Fund", monthDate: "2026-03-01", balance: "14000" },
  ],

  contributionAccounts: [
    {
      personName: "Morgan",
      accountType: "401k",
      taxTreatment: "pre_tax",
      contributionMethod: "percent_of_salary",
      contributionValue: "23",
      employerMatchType: "percent_of_contribution",
      employerMatchValue: "100",
      employerMaxMatchPct: "6",
      perfAccountLabel: "401(k) Mega",
    },
    {
      personName: "Morgan",
      accountType: "ira",
      taxTreatment: "tax_free",
      contributionMethod: "fixed_annual",
      contributionValue: "7000",
      employerMatchType: "none",
      employerMatchValue: null,
      employerMaxMatchPct: null,
      perfAccountLabel: "Roth IRA",
    },
    {
      personName: "Morgan",
      accountType: "hsa",
      taxTreatment: "hsa",
      contributionMethod: "fixed_annual",
      contributionValue: "4150",
      employerMatchType: "none",
      employerMatchValue: null,
      employerMaxMatchPct: null,
      perfAccountLabel: "HSA",
    },
    {
      personName: "Morgan",
      accountType: "brokerage",
      taxTreatment: "after_tax",
      contributionMethod: "fixed_annual",
      contributionValue: "60000",
      employerMatchType: "none",
      employerMatchValue: null,
      employerMaxMatchPct: null,
      perfAccountLabel: "Taxable Brokerage",
      parentCategory: "Retirement",
    },
  ],

  portfolioSnapshots: [{ snapshotDate: "2026-03-01" }],

  portfolioAccounts: [
    {
      institution: "FAANG",
      accountType: "401k",
      taxType: "preTax",
      amount: "343000",
      label: "Mega",
      ownerPersonName: "Morgan",
      perfAccountLabel: "401(k) Mega",
    },
    {
      institution: "Vanguard",
      accountType: "ira",
      taxType: "taxFree",
      amount: "95000",
      label: null,
      ownerPersonName: "Morgan",
      perfAccountLabel: "Roth IRA",
    },
    {
      institution: "Fidelity",
      accountType: "hsa",
      taxType: "hsa",
      amount: "40500",
      label: null,
      ownerPersonName: "Morgan",
      perfAccountLabel: "HSA",
    },
    {
      institution: "Schwab",
      accountType: "brokerage",
      taxType: "afterTax",
      amount: "450000",
      label: "Taxable",
      ownerPersonName: "Morgan",
      parentCategory: "Retirement",
      perfAccountLabel: "Taxable Brokerage",
    },
  ],

  performanceAccounts: [
    {
      institution: "FAANG",
      accountType: "401k",
      accountLabel: "401(k) Mega",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "Vanguard",
      accountType: "ira",
      accountLabel: "Roth IRA",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "Fidelity",
      accountType: "hsa",
      accountLabel: "HSA",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "Schwab",
      accountType: "brokerage",
      accountLabel: "Taxable Brokerage",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
  ],

  annualPerformance: [
    {
      category: "401k/IRA",
      year: 2023,
      beginningBalance: "630000",
      totalContributions: "130000",
      yearlyGainLoss: "55000",
      endingBalance: "815000",
      annualReturnPct: "8.7",
      employerContributions: "15000",
      fees: "1000",
      lifetimeGains: "190000",
      lifetimeContributions: "585000",
      lifetimeMatch: "60000",
    },
    {
      category: "401k/IRA",
      year: 2024,
      beginningBalance: "815000",
      totalContributions: "101150",
      yearlyGainLoss: "53700",
      endingBalance: "772850",
      annualReturnPct: "0.059",
      employerContributions: "10000",
      fees: "600",
      lifetimeGains: "243700",
      lifetimeContributions: "686150",
      lifetimeMatch: "70000",
    },
    {
      category: "401k/IRA",
      year: 2025,
      beginningBalance: "772850",
      totalContributions: "101650",
      yearlyGainLoss: "17300",
      endingBalance: "891800",
      annualReturnPct: "0.019",
      employerContributions: "10500",
      fees: "650",
      lifetimeGains: "261000",
      lifetimeContributions: "787800",
      lifetimeMatch: "80500",
    },
  ],

  retirementSettings: {
    personName: "Morgan",
    retirementAge: 45,
    endAge: 95,
    returnAfterRetirement: "0.05",
    annualInflation: "0.03",
    salaryAnnualIncrease: "0.04",
    withdrawalRate: "0.035",
    withdrawalStrategy: "vanguard_dynamic",
    socialSecurityMonthly: "2800",
    ssStartAge: 67,
  },

  returnRates: [
    { age: 25, rateOfReturn: "0.09" },
    { age: 45, rateOfReturn: "0.07" },
    { age: 60, rateOfReturn: "0.06" },
    { age: 75, rateOfReturn: "0.05" },
  ],

  mortgageLoans: [
    {
      name: "Condo",
      isActive: true,
      principalAndInterest: "1800",
      interestRate: "0.0375",
      termYears: 30,
      originalLoanAmount: "280000",
      firstPaymentDate: "2020-01-01",
      propertyValuePurchase: "380000",
      propertyValueEstimated: null,
    },
  ],

  netWorthAnnual: [
    {
      yearEndDate: "2022-12-31",
      grossIncome: "220000",
      combinedAgi: "190000",
      cash: "25000",
      houseValue: "320000",
      retirementTotal: "450000",
      portfolioTotal: "450000",
      mortgageBalance: "260000",
    },
    {
      yearEndDate: "2023-12-31",
      grossIncome: "230000",
      combinedAgi: "198000",
      cash: "30000",
      houseValue: "350000",
      retirementTotal: "580000",
      portfolioTotal: "580000",
      mortgageBalance: "245000",
    },
    {
      yearEndDate: "2024-12-31",
      grossIncome: "235000",
      combinedAgi: "200000",
      cash: "38000",
      houseValue: "365000",
      retirementTotal: "720000",
      portfolioTotal: "720000",
      mortgageBalance: "230000",
    },
    {
      yearEndDate: "2025-12-31",
      grossIncome: "240000",
      combinedAgi: "205000",
      cash: "44000",
      houseValue: "380000",
      retirementTotal: "850000",
      portfolioTotal: "850000",
      mortgageBalance: "220000",
    },
  ],

  accountPerformance: [
    // 401k
    {
      year: 2024,
      institution: "FAANG",
      accountLabel: "401(k) Mega",
      ownerPersonName: "Morgan",
      beginningBalance: "240000",
      totalContributions: "30000",
      yearlyGainLoss: "22000",
      endingBalance: "292000",
      annualReturnPct: "8.2",
      employerContributions: "10000",
      fees: "400",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) Mega",
    },
    {
      year: 2025,
      institution: "FAANG",
      accountLabel: "401(k) Mega",
      ownerPersonName: "Morgan",
      beginningBalance: "292000",
      totalContributions: "30500",
      yearlyGainLoss: "6500",
      endingBalance: "329000",
      annualReturnPct: "2.1",
      employerContributions: "10500",
      fees: "450",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) Mega",
    },
    // Roth IRA
    {
      year: 2024,
      institution: "Vanguard",
      accountLabel: "Roth IRA",
      ownerPersonName: "Morgan",
      beginningBalance: "70000",
      totalContributions: "7000",
      yearlyGainLoss: "6500",
      endingBalance: "83500",
      annualReturnPct: "8.4",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA",
    },
    {
      year: 2025,
      institution: "Vanguard",
      accountLabel: "Roth IRA",
      ownerPersonName: "Morgan",
      beginningBalance: "83500",
      totalContributions: "7000",
      yearlyGainLoss: "2000",
      endingBalance: "92500",
      annualReturnPct: "2.3",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA",
    },
    // HSA
    {
      year: 2024,
      institution: "Fidelity",
      accountLabel: "HSA",
      ownerPersonName: "Morgan",
      beginningBalance: "28000",
      totalContributions: "4150",
      yearlyGainLoss: "2200",
      endingBalance: "34350",
      annualReturnPct: "7.0",
      employerContributions: "0",
      fees: "50",
      parentCategory: "Retirement",
      perfAccountLabel: "HSA",
    },
    {
      year: 2025,
      institution: "Fidelity",
      accountLabel: "HSA",
      ownerPersonName: "Morgan",
      beginningBalance: "34350",
      totalContributions: "4150",
      yearlyGainLoss: "800",
      endingBalance: "39300",
      annualReturnPct: "2.2",
      employerContributions: "0",
      fees: "50",
      parentCategory: "Retirement",
      perfAccountLabel: "HSA",
    },
    // Taxable Brokerage
    {
      year: 2024,
      institution: "Schwab",
      accountLabel: "Taxable Brokerage",
      ownerPersonName: "Morgan",
      beginningBalance: "280000",
      totalContributions: "60000",
      yearlyGainLoss: "23000",
      endingBalance: "363000",
      annualReturnPct: "6.8",
      employerContributions: "0",
      fees: "150",
      parentCategory: "Retirement",
      perfAccountLabel: "Taxable Brokerage",
    },
    {
      year: 2025,
      institution: "Schwab",
      accountLabel: "Taxable Brokerage",
      ownerPersonName: "Morgan",
      beginningBalance: "363000",
      totalContributions: "60000",
      yearlyGainLoss: "8000",
      endingBalance: "431000",
      annualReturnPct: "2.1",
      employerContributions: "0",
      fees: "150",
      parentCategory: "Retirement",
      perfAccountLabel: "Taxable Brokerage",
    },
    // 2026 YTD (Q1)
    {
      year: 2026,
      institution: "FAANG",
      accountLabel: "401(k) Mega",
      ownerPersonName: "Morgan",
      beginningBalance: "329000",
      totalContributions: "7625",
      yearlyGainLoss: "3750",
      endingBalance: "343000",
      annualReturnPct: "1.1",
      employerContributions: "2625",
      fees: "112",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k) Mega",
    },
    {
      year: 2026,
      institution: "Vanguard",
      accountLabel: "Roth IRA",
      ownerPersonName: "Morgan",
      beginningBalance: "92500",
      totalContributions: "1750",
      yearlyGainLoss: "750",
      endingBalance: "95000",
      annualReturnPct: "0.8",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA",
    },
    {
      year: 2026,
      institution: "Fidelity",
      accountLabel: "HSA",
      ownerPersonName: "Morgan",
      beginningBalance: "39300",
      totalContributions: "1038",
      yearlyGainLoss: "162",
      endingBalance: "40500",
      annualReturnPct: "0.4",
      employerContributions: "0",
      fees: "12",
      parentCategory: "Retirement",
      perfAccountLabel: "HSA",
    },
    {
      year: 2026,
      institution: "Schwab",
      accountLabel: "Taxable Brokerage",
      ownerPersonName: "Morgan",
      beginningBalance: "431000",
      totalContributions: "15000",
      yearlyGainLoss: "4000",
      endingBalance: "450000",
      annualReturnPct: "0.9",
      employerContributions: "0",
      fees: "38",
      parentCategory: "Retirement",
      perfAccountLabel: "Taxable Brokerage",
    },
  ],

  otherAssetItems: [
    {
      name: "Tesla Model 3",
      year: 2024,
      value: "28000",
      note: "Purchased 2022",
    },
    { name: "Tesla Model 3", year: 2025, value: "24000", note: "Depreciation" },
    { name: "Crypto (BTC/ETH)", year: 2024, value: "15000", note: null },
    { name: "Crypto (BTC/ETH)", year: 2025, value: "18000", note: null },
  ],

  propertyTaxes: [
    {
      loanName: "Condo",
      year: 2023,
      assessedValue: "350000",
      taxAmount: "4200",
      note: null,
    },
    {
      loanName: "Condo",
      year: 2024,
      assessedValue: "365000",
      taxAmount: "4380",
      note: null,
    },
    {
      loanName: "Condo",
      year: 2025,
      assessedValue: "375000",
      taxAmount: "4500",
      note: null,
    },
  ],

  homeImprovements: [
    { year: 2023, description: "Kitchen backsplash", cost: "3500" },
    { year: 2024, description: "New HVAC system", cost: "8500" },
  ],

  appSettings: [
    { key: "budget_active_column", value: 0 },
    { key: "efund_budget_column", value: 0 },
  ],
};
