import type { DemoProfile } from "../types";

export const singleIncomeProfile: DemoProfile = {
  slug: "single-income",
  name: "Young Professional",
  description:
    "Single income, early career, building an emergency fund and starting to invest.",
  keyStats: { income: "$85,000", portfolioSize: "$45,000", savingsRate: "18%" },

  people: [{ name: "Alex", dateOfBirth: "1996-06-15", isPrimaryUser: true }],

  jobs: [
    {
      personName: "Alex",
      employerName: "TechCorp",
      title: "Software Engineer",
      annualSalary: "85000",
      payPeriod: "biweekly",
      payWeek: "even",
      startDate: "2020-06-01",
      anchorPayDate: "2026-01-10",
      endDate: null,
      bonusPercent: "0",
      bonusMonth: null,
      w4FilingStatus: "Single",
    },
  ],

  budgetProfiles: [
    {
      name: "Default",
      isActive: true,
      columnLabels: ["Lean", "Normal", "Comfortable"],
      columnMonths: null,
    },
  ],

  budgetItems: [
    {
      profileName: "Default",
      category: "Housing",
      subcategory: "Rent",
      isEssential: true,
      amounts: [1400, 1400, 1400],
    },
    {
      profileName: "Default",
      category: "Housing",
      subcategory: "Utilities",
      isEssential: true,
      amounts: [120, 150, 150],
    },
    {
      profileName: "Default",
      category: "Housing",
      subcategory: "Insurance",
      isEssential: true,
      amounts: [30, 30, 30],
    },
    {
      profileName: "Default",
      category: "Food",
      subcategory: "Groceries",
      isEssential: true,
      amounts: [300, 400, 500],
    },
    {
      profileName: "Default",
      category: "Food",
      subcategory: "Dining Out",
      isEssential: false,
      amounts: [50, 150, 250],
    },
    {
      profileName: "Default",
      category: "Transportation",
      subcategory: "Car Payment",
      isEssential: true,
      amounts: [350, 350, 350],
    },
    {
      profileName: "Default",
      category: "Transportation",
      subcategory: "Gas & Insurance",
      isEssential: true,
      amounts: [150, 180, 200],
    },
    {
      profileName: "Default",
      category: "Health",
      subcategory: "Insurance Premium",
      isEssential: true,
      amounts: [100, 100, 100],
    },
    {
      profileName: "Default",
      category: "Personal",
      subcategory: "Subscriptions",
      isEssential: false,
      amounts: [20, 50, 80],
    },
    {
      profileName: "Default",
      category: "Personal",
      subcategory: "Entertainment",
      isEssential: false,
      amounts: [50, 100, 200],
    },
    {
      profileName: "Default",
      category: "Personal",
      subcategory: "Clothing",
      isEssential: false,
      amounts: [25, 50, 100],
    },
  ],

  savingsGoals: [
    {
      name: "Emergency Fund",
      targetAmount: null,
      targetMonths: 4,
      priority: 1,
      isEmergencyFund: true,
      monthlyContribution: "400",
      allocationPercent: null,
    },
    {
      name: "Vacation",
      targetAmount: "3000",
      targetMonths: null,
      priority: 2,
      isEmergencyFund: false,
      monthlyContribution: "200",
      allocationPercent: null,
    },
    {
      name: "New Laptop",
      targetAmount: "2000",
      targetMonths: null,
      priority: 3,
      isEmergencyFund: false,
      monthlyContribution: "100",
      allocationPercent: null,
    },
  ],

  savingsMonthly: [
    { goalName: "Emergency Fund", monthDate: "2025-04-01", balance: "2000" },
    { goalName: "Emergency Fund", monthDate: "2025-05-01", balance: "2300" },
    { goalName: "Emergency Fund", monthDate: "2025-06-01", balance: "2600" },
    { goalName: "Emergency Fund", monthDate: "2025-07-01", balance: "2900" },
    { goalName: "Emergency Fund", monthDate: "2025-08-01", balance: "3200" },
    { goalName: "Emergency Fund", monthDate: "2025-09-01", balance: "3500" },
    { goalName: "Emergency Fund", monthDate: "2025-10-01", balance: "3800" },
    { goalName: "Emergency Fund", monthDate: "2025-11-01", balance: "4100" },
    { goalName: "Emergency Fund", monthDate: "2025-12-01", balance: "4400" },
    { goalName: "Emergency Fund", monthDate: "2026-01-01", balance: "4700" },
    { goalName: "Emergency Fund", monthDate: "2026-02-01", balance: "5000" },
    { goalName: "Emergency Fund", monthDate: "2026-03-01", balance: "5200" },
    { goalName: "Vacation", monthDate: "2025-04-01", balance: "500" },
    { goalName: "Vacation", monthDate: "2025-05-01", balance: "640" },
    { goalName: "Vacation", monthDate: "2025-06-01", balance: "780" },
    { goalName: "Vacation", monthDate: "2025-07-01", balance: "920" },
    { goalName: "Vacation", monthDate: "2025-08-01", balance: "1060" },
    { goalName: "Vacation", monthDate: "2025-09-01", balance: "1200" },
    { goalName: "Vacation", monthDate: "2025-10-01", balance: "1340" },
    { goalName: "Vacation", monthDate: "2025-11-01", balance: "1480" },
    { goalName: "Vacation", monthDate: "2025-12-01", balance: "1620" },
    { goalName: "Vacation", monthDate: "2026-01-01", balance: "1760" },
    { goalName: "Vacation", monthDate: "2026-02-01", balance: "1880" },
    { goalName: "Vacation", monthDate: "2026-03-01", balance: "2000" },
    { goalName: "New Laptop", monthDate: "2025-04-01", balance: "0" },
    { goalName: "New Laptop", monthDate: "2025-05-01", balance: "110" },
    { goalName: "New Laptop", monthDate: "2025-06-01", balance: "220" },
    { goalName: "New Laptop", monthDate: "2025-07-01", balance: "330" },
    { goalName: "New Laptop", monthDate: "2025-08-01", balance: "440" },
    { goalName: "New Laptop", monthDate: "2025-09-01", balance: "550" },
    { goalName: "New Laptop", monthDate: "2025-10-01", balance: "660" },
    { goalName: "New Laptop", monthDate: "2025-11-01", balance: "770" },
    { goalName: "New Laptop", monthDate: "2025-12-01", balance: "880" },
    { goalName: "New Laptop", monthDate: "2026-01-01", balance: "990" },
    { goalName: "New Laptop", monthDate: "2026-02-01", balance: "1100" },
    { goalName: "New Laptop", monthDate: "2026-03-01", balance: "1200" },
  ],

  contributionAccounts: [
    {
      personName: "Alex",
      accountType: "401k",
      taxTreatment: "pre_tax",
      contributionMethod: "percent_of_salary",
      contributionValue: "10",
      employerMatchType: "percent_of_contribution",
      employerMatchValue: "50",
      employerMaxMatchPct: "6",
      perfAccountLabel: "401(k) - TechCorp",
    },
    {
      personName: "Alex",
      accountType: "ira",
      taxTreatment: "tax_free",
      contributionMethod: "fixed_annual",
      contributionValue: "7000",
      employerMatchType: "none",
      employerMatchValue: null,
      employerMaxMatchPct: null,
      perfAccountLabel: "Roth IRA",
    },
  ],

  portfolioSnapshots: [{ snapshotDate: "2026-03-01" }],

  portfolioAccounts: [
    {
      institution: "TechCorp",
      accountType: "401k",
      taxType: "preTax",
      amount: "78000",
      label: null,
      ownerPersonName: "Alex",
      perfAccountLabel: "401(k) - TechCorp",
    },
    {
      institution: "Vanguard",
      accountType: "ira",
      taxType: "taxFree",
      amount: "28000",
      label: null,
      ownerPersonName: "Alex",
      perfAccountLabel: "Roth IRA",
    },
  ],

  performanceAccounts: [
    {
      institution: "TechCorp",
      accountType: "401k",
      accountLabel: "401(k) - TechCorp",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
    {
      institution: "Vanguard",
      accountType: "ira",
      accountLabel: "Roth IRA",
      ownershipType: "individual",
      parentCategory: "Retirement",
      label: null,
      isActive: true,
    },
  ],

  annualPerformance: [
    {
      category: "Retirement",
      year: 2023,
      beginningBalance: "25000",
      totalContributions: "15000",
      yearlyGainLoss: "3200",
      endingBalance: "43200",
      annualReturnPct: "8.0",
      employerContributions: "3400",
      fees: "100",
      lifetimeGains: "5200",
      lifetimeContributions: "35000",
      lifetimeMatch: "6800",
    },
    {
      category: "Retirement",
      year: 2024,
      beginningBalance: "23000",
      totalContributions: "15500",
      yearlyGainLoss: "2550",
      endingBalance: "35000",
      annualReturnPct: "0.066",
      employerContributions: "2550",
      fees: "50",
      lifetimeGains: "2550",
      lifetimeContributions: "15500",
      lifetimeMatch: "2550",
    },
    {
      category: "Retirement",
      year: 2025,
      beginningBalance: "35000",
      totalContributions: "15500",
      yearlyGainLoss: "3555",
      endingBalance: "45000",
      annualReturnPct: "0.070",
      employerContributions: "2550",
      fees: "55",
      lifetimeGains: "6105",
      lifetimeContributions: "31000",
      lifetimeMatch: "5100",
    },
  ],

  retirementSettings: {
    personName: "Alex",
    retirementAge: 62,
    endAge: 90,
    returnAfterRetirement: "0.05",
    annualInflation: "0.03",
    salaryAnnualIncrease: "0.03",
    withdrawalRate: "0.04",
    withdrawalStrategy: "fixed",
    socialSecurityMonthly: "2200",
    ssStartAge: 67,
  },

  returnRates: [
    { age: 25, rateOfReturn: "0.08" },
    { age: 50, rateOfReturn: "0.07" },
    { age: 62, rateOfReturn: "0.06" },
    { age: 75, rateOfReturn: "0.05" },
  ],

  mortgageLoans: [],

  accountPerformance: [
    {
      year: 2024,
      institution: "TechCorp",
      accountLabel: "401(k)",
      ownerPersonName: "Alex",
      beginningBalance: "43200",
      totalContributions: "11500",
      yearlyGainLoss: "4800",
      endingBalance: "59500",
      annualReturnPct: "8.8",
      employerContributions: "3400",
      fees: "80",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k)",
    },
    {
      year: 2025,
      institution: "TechCorp",
      accountLabel: "401(k)",
      ownerPersonName: "Alex",
      beginningBalance: "59500",
      totalContributions: "12000",
      yearlyGainLoss: "1500",
      endingBalance: "73000",
      annualReturnPct: "2.1",
      employerContributions: "3600",
      fees: "90",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k)",
    },
    {
      year: 2024,
      institution: "Vanguard",
      accountLabel: "Roth IRA",
      ownerPersonName: "Alex",
      beginningBalance: "10000",
      totalContributions: "7000",
      yearlyGainLoss: "1400",
      endingBalance: "18400",
      annualReturnPct: "8.2",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA",
    },
    {
      year: 2025,
      institution: "Vanguard",
      accountLabel: "Roth IRA",
      ownerPersonName: "Alex",
      beginningBalance: "18400",
      totalContributions: "7000",
      yearlyGainLoss: "500",
      endingBalance: "25900",
      annualReturnPct: "2.0",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA",
    },
    // 2026 YTD (Q1)
    {
      year: 2026,
      institution: "TechCorp",
      accountLabel: "401(k)",
      ownerPersonName: "Alex",
      beginningBalance: "73000",
      totalContributions: "3000",
      yearlyGainLoss: "1100",
      endingBalance: "78000",
      annualReturnPct: "1.5",
      employerContributions: "900",
      fees: "22",
      parentCategory: "Retirement",
      perfAccountLabel: "401(k)",
    },
    {
      year: 2026,
      institution: "Vanguard",
      accountLabel: "Roth IRA",
      ownerPersonName: "Alex",
      beginningBalance: "25900",
      totalContributions: "1750",
      yearlyGainLoss: "350",
      endingBalance: "28000",
      annualReturnPct: "1.3",
      employerContributions: "0",
      fees: "0",
      parentCategory: "Retirement",
      perfAccountLabel: "Roth IRA",
    },
  ],

  otherAssetItems: [
    { name: "Honda Civic", year: 2024, value: "18000", note: "Purchased 2021" },
    { name: "Honda Civic", year: 2025, value: "15000", note: "Depreciation" },
  ],

  propertyTaxes: [],
  homeImprovements: [],

  netWorthAnnual: [
    {
      yearEndDate: "2023-12-31",
      grossIncome: "85000",
      combinedAgi: "76500",
      cash: "3000",
      houseValue: "0",
      retirementTotal: "18000",
      portfolioTotal: "18000",
      mortgageBalance: "0",
    },
    {
      yearEndDate: "2024-12-31",
      grossIncome: "85000",
      combinedAgi: "76500",
      cash: "5500",
      houseValue: "0",
      retirementTotal: "77900",
      portfolioTotal: "77900",
      mortgageBalance: "0",
    },
    {
      yearEndDate: "2025-12-31",
      grossIncome: "85000",
      combinedAgi: "76500",
      cash: "7200",
      houseValue: "0",
      retirementTotal: "98900",
      portfolioTotal: "98900",
      mortgageBalance: "0",
    },
  ],

  appSettings: [
    { key: "budget_active_column", value: 1 },
    { key: "efund_budget_column", value: 1 },
  ],
};
